### ISSUE TITLE
Optional buildpack value lost, or spec is unclear.

### ISSUE THREAD

**Issue by squee1945** [buildpack/lifecycle#115]
During the ordering of buildpacks according to the groups, the optional bit is not correctly set. This line [1] takes the optional bit from the group deserialization (the Buildpack data structure is reused both for the backpack base definition and the group definition).

So, either 
  (1) line [1] is incorrect and should be removed (i.e., `optional` can only be specified on the buildpack itself),
  (2) it is allowed to override buildpack definition in the group definition, in which case we need to distinguish between "false" and "not specified" for `optional`, or
  (3) `optional` should only be specified on the group.

In all cases, I think the spec needs to clarify as I couldn't find it.

[1] https://github.com/buildpack/lifecycle/blob/master/map.go#L54

**Comment by sclevine** [comment]
The `BuildpackMap` is constructed from the `buildpack.toml` files in each buildpack on the filesystem[1]. It has no concept of `Optional` (even though it re-uses the `Buildpack` struct with that field).

Each buildpack in `BuildpackMap` can be referenced multiple times in order.toml or group.toml. When `lookup` is called in `ReadOrder`, we copy the `optional` field value onto the value from the `BuildpackMap` before returning it, so that you can convert an order.toml file that is missing the info from the buildpack.toml files to a fully-hydrated structure in memory. In the case of group.toml/`ReadGroup`, the copying of the `Optional` field is meaningless, because optionality isn't relevant after the detection process (which removes optional buildpacks that failed detection).

This code could be tidied up a bit (perhaps by creating different types of buildpack structs for different use cases), but I think the behavior (and spec) are both accurate. Are you seeing otherwise in the behavior of the lifecycle?

[1] https://github.com/buildpack/lifecycle/blob/master/map.go#L21
[2] https://github.com/buildpack/spec/blob/master/platform.md#data-format

**Comment by ekcasey** [comment]
@squee1945 @sclevine 

Sounds like this is a critique of the code readability rather than a bug. I'm inclined to close unless anyone feels strongly to the contrary (we can certainly refactor for clarity but this issue feels misleading)

**Comment by squee1945** [comment]
I think it just needs some documentation in the spec.

**Comment by ekcasey** [comment]
@squee1945 I am closing this issue. Feel free to open an issue or PR on the spec repo if you feel that the specification lacks clarity.
