### ISSUE TITLE
use sh instead of bash

### ISSUE THREAD

**Issue by MartinForReal** [buildpack/lifecycle#155]
some base image (such as alpine and distroless) may not have bash installed. And 

```
Error: failed to launch: exec: no such file or directory
```

error msg above is hard to locate the root cause until I read the source code.

**Comment by sclevine** [comment]
See:
https://github.com/buildpack/spec/pull/50
https://github.com/buildpack/lifecycle/pull/148

Different shells support different syntax. We've standardized on bash so that `profile.d`/`.profile` scripts don't have subtly different behavior on different stacks. With the above PRs, a buildpack can opt to set the start command directly (without a shell) and skip the `profile.d`/`.profile` functionality.
